global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'watchtower-auth'
    static_configs:
      - targets: ['auth-service:4004']

  - job_name: 'watchtower-shipment'
    static_configs:
      - targets: ['shipment-service:5001']

  - job_name: 'watchtower-inventory'
    static_configs:
      - targets: ['inventory-service:8081']

  - job_name: 'watchtower-analytics'
    static_configs:
      - targets: ['analytics-service:4005']
